### PR TITLE
Added Tasks, Shop, MomoTalk

### PR DESCRIPTION
**Pull request by RedDeadDepresso**
Hi, I had some free time so I decided to familiarise myself with the Alas framework. I attempted to implement some simple features using https://github.com/baas-pro/baas as a reference such as Tasks, Shop, MomoTalk. However, I encountered issues with Shop and MomoTalk.

Shop:
- The swipes are imprecise, and clicks happen too quickly in the self.select_items() method within the shop/ui.py file. This is because of my unfamiliarity with the Alas framework.

MomoTalk:
- The switches doesn't work.
- AAS cannot locate certain buttons even when they are visible on the screen. For example, the MESSAGE_ON, UNREAD, and SORT_ON buttons in self.open_momotalk and self.sort_messages. I ignored the problem by always clicking on the buttons but it would be better to check first they appear and not do unnecessary actions.
- Timing is inaccurate in the self.chat method due to self.wait_until_stable.
- I attempted to check the presence of a red notification badge for MomoTalk on the main page by using self.match_color with NOTIFICATION_BADGE and FIRST_UNREAD in self.open_messages and self.check_first_student. I'm not sure if it is the correct way.

All mentioned methods are in momotalk/ui.py file.

Understanding the code shouldn't be an issue for you, as I followed the same structure you used in other modules. Also I reused some of your methods, however with different names. I can fix all these problems myself if you can help me and provide feedback.

### CODE REVIEW

**Comment by TheFunny** [comment]
Thanks for the contribution. I can try help you with your problems.

Shop:
- The `vector_range` is for generating a vector with its scale based on the swipe area. For example, if I set the range to `(0.4, 0.6)`, the script will firstly generate a number of scale using uniform normal distribution (generally speaking, a number at around 0.5 in this case). Then, it multiplies the scale with height of swipe area and output a vector. Actually it's not necessary but I still decide to leave it there. If you need precise swipe you can just skip this process and use a constant scale directly. Another reason that the swipe is not accurate is because of the rebound of swipe in game, I guess.
- For clicking too quickly, there may be multiple reasons and currently I'm not sure about that. But I can try testing and solving that after merge.

Momotalk:
- I've also encountered with the problem that the switch doesn't work. One possible reason I guess is that the `appear` method in switch uses match template, which may not be sensitive to light and dark change of the button. However, you mentioned that all switchs in momotalk do not work. There may be other reasons. If you can't solve that, I can help test and solve after merge.
- Currently I'm unsure about the reason why AAS can't detect existed button. I can investigate this later.
- Actually `wait_until_stable` is not recommended to be used by developer of ALAS. If that problem does not have serious effect, you can ignore it now. Or just don't use `wait_until_stable` and replace it with recognition of other objects.
- Match color should be fine. If any problem occurs, we may solve that later.

Btw, there is another momotalk icon when it's student's birthday. I'll add that later.

**Comment by RedDeadDepresso** [comment]
I would be very grateful if you could merge and test as I'm stuck and have no idea how to fix them. The logic is correct for both shop and momotalk, the only thing to do is improve the timing and solve the problem of buttons and switches not being detected in momotalk.

**Review by TheFunny — APPROVED** [review]

**Comment by TheFunny** [comment]
Thanks. I'll be adding assets for JP in a few days.

**Comment by RedDeadDepresso** [comment]
Thanks, if you want and like Missions/Commissions/Event in BAAuto I can try to write it for AAS and refactor MCE-Manager. The code probably won't be optimized but at least I hope it can help you in some way.

**Comment by RedDeadDepresso** [comment]
Also, another problem I discovered is that in tasks the while loop breaks after self.ui_additional() when the Claim All and Claim buttons are still yellow. Maybe you should add a delay after self.ui_additional().

**Comment by TheFunny** [comment]
> Thanks, if you want and like Missions/Commissions/Event in BAAuto I can try to write it for AAS and refactor MCE-Manager. The code probably won't be optimized but at least I hope it can help you in some way.

Implementing these functions shouldn't be so difficult using existing modules in AAS, so my idea is to try completing in ALAS framework. The only problem is that it may be complicated for user to select the missions they want to sweep. If you can implement MCE seamlessly into AAS, it should be fine.

> Also, another problem I discovered is that in tasks the while loop breaks after self.ui_additional() when the Claim All and Claim buttons are still yellow. Maybe you should add a delay after self.ui_additional().

I'll check that later.

**Comment by RedDeadDepresso** [comment]
I am finding it easy and have already uploaded the assets and written a rough draft, so I think I can finish in two days. I will make a pull request after you fixed the bugs in other tasks.

**Comment by TheFunny** [comment]
I've fixed switch for message and sort in momotalk in latest dev branch. Now it should work properly. Task exiting condition has been changed so that it now ends after detecting claimed button.

**Comment by RedDeadDepresso** [comment]
Merry Christmas! I have implemented Mission/Commissions/Event successfully and from my testing it seems to work well. If you want I can make a pull request.

**Comment by TheFunny** [comment]
Merry Christmas! You can directly make a PR if it's ready. I'll review when I'm free.

**Pull request merged**
